// Generated by gencpp from file backend/Bboxes.msg
// DO NOT EDIT!


#ifndef BACKEND_MESSAGE_BBOXES_H
#define BACKEND_MESSAGE_BBOXES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace backend
{
template <class ContainerAllocator>
struct Bboxes_
{
  typedef Bboxes_<ContainerAllocator> Type;

  Bboxes_()
    : header()
    , data()
    , stationID()
    , sensorID()  {
    }
  Bboxes_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)
    , stationID(_alloc)
    , sensorID(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _data_type;
  _data_type data;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _stationID_type;
  _stationID_type stationID;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _sensorID_type;
  _sensorID_type sensorID;





  typedef boost::shared_ptr< ::backend::Bboxes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::backend::Bboxes_<ContainerAllocator> const> ConstPtr;

}; // struct Bboxes_

typedef ::backend::Bboxes_<std::allocator<void> > Bboxes;

typedef boost::shared_ptr< ::backend::Bboxes > BboxesPtr;
typedef boost::shared_ptr< ::backend::Bboxes const> BboxesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::backend::Bboxes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::backend::Bboxes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::backend::Bboxes_<ContainerAllocator1> & lhs, const ::backend::Bboxes_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data &&
    lhs.stationID == rhs.stationID &&
    lhs.sensorID == rhs.sensorID;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::backend::Bboxes_<ContainerAllocator1> & lhs, const ::backend::Bboxes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace backend

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::backend::Bboxes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::backend::Bboxes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::backend::Bboxes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::backend::Bboxes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::backend::Bboxes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::backend::Bboxes_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::backend::Bboxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "475569134d54a5f2a487b7d6d6daa81c";
  }

  static const char* value(const ::backend::Bboxes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x475569134d54a5f2ULL;
  static const uint64_t static_value2 = 0xa487b7d6d6daa81cULL;
};

template<class ContainerAllocator>
struct DataType< ::backend::Bboxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "backend/Bboxes";
  }

  static const char* value(const ::backend::Bboxes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::backend::Bboxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32[] data\n"
"int16[] stationID\n"
"int16[] sensorID\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::backend::Bboxes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::backend::Bboxes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
      stream.next(m.stationID);
      stream.next(m.sensorID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Bboxes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::backend::Bboxes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::backend::Bboxes_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
    s << indent << "stationID[]" << std::endl;
    for (size_t i = 0; i < v.stationID.size(); ++i)
    {
      s << indent << "  stationID[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.stationID[i]);
    }
    s << indent << "sensorID[]" << std::endl;
    for (size_t i = 0; i < v.sensorID.size(); ++i)
    {
      s << indent << "  sensorID[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.sensorID[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BACKEND_MESSAGE_BBOXES_H
