// Generated by gencpp from file backend/Images.msg
// DO NOT EDIT!


#ifndef BACKEND_MESSAGE_IMAGES_H
#define BACKEND_MESSAGE_IMAGES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>

namespace backend
{
template <class ContainerAllocator>
struct Images_
{
  typedef Images_<ContainerAllocator> Type;

  Images_()
    : number(0)
    , img1()
    , img2()
    , img3()
    , img4()  {
    }
  Images_(const ContainerAllocator& _alloc)
    : number(0)
    , img1(_alloc)
    , img2(_alloc)
    , img3(_alloc)
    , img4(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _number_type;
  _number_type number;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _img1_type;
  _img1_type img1;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _img2_type;
  _img2_type img2;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _img3_type;
  _img3_type img3;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _img4_type;
  _img4_type img4;





  typedef boost::shared_ptr< ::backend::Images_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::backend::Images_<ContainerAllocator> const> ConstPtr;

}; // struct Images_

typedef ::backend::Images_<std::allocator<void> > Images;

typedef boost::shared_ptr< ::backend::Images > ImagesPtr;
typedef boost::shared_ptr< ::backend::Images const> ImagesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::backend::Images_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::backend::Images_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::backend::Images_<ContainerAllocator1> & lhs, const ::backend::Images_<ContainerAllocator2> & rhs)
{
  return lhs.number == rhs.number &&
    lhs.img1 == rhs.img1 &&
    lhs.img2 == rhs.img2 &&
    lhs.img3 == rhs.img3 &&
    lhs.img4 == rhs.img4;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::backend::Images_<ContainerAllocator1> & lhs, const ::backend::Images_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace backend

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::backend::Images_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::backend::Images_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::backend::Images_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::backend::Images_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::backend::Images_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::backend::Images_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::backend::Images_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4083fda66ae96557bfd28f8a92b13da6";
  }

  static const char* value(const ::backend::Images_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4083fda66ae96557ULL;
  static const uint64_t static_value2 = 0xbfd28f8a92b13da6ULL;
};

template<class ContainerAllocator>
struct DataType< ::backend::Images_<ContainerAllocator> >
{
  static const char* value()
  {
    return "backend/Images";
  }

  static const char* value(const ::backend::Images_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::backend::Images_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 number\n"
"sensor_msgs/Image img1\n"
"sensor_msgs/Image img2\n"
"sensor_msgs/Image img3\n"
"sensor_msgs/Image img4\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::backend::Images_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::backend::Images_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
      stream.next(m.img1);
      stream.next(m.img2);
      stream.next(m.img3);
      stream.next(m.img4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Images_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::backend::Images_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::backend::Images_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<int16_t>::stream(s, indent + "  ", v.number);
    s << indent << "img1: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.img1);
    s << indent << "img2: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.img2);
    s << indent << "img3: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.img3);
    s << indent << "img4: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.img4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BACKEND_MESSAGE_IMAGES_H
