// Generated by gencpp from file backend/Person.msg
// DO NOT EDIT!


#ifndef BACKEND_MESSAGE_PERSON_H
#define BACKEND_MESSAGE_PERSON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <backend/Bodypart.h>

namespace backend
{
template <class ContainerAllocator>
struct Person_
{
  typedef Person_<ContainerAllocator> Type;

  Person_()
    : stationID(0)
    , sensorID(0)
    , bodyParts()  {
    }
  Person_(const ContainerAllocator& _alloc)
    : stationID(0)
    , sensorID(0)
    , bodyParts(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _stationID_type;
  _stationID_type stationID;

   typedef int16_t _sensorID_type;
  _sensorID_type sensorID;

   typedef std::vector< ::backend::Bodypart_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::backend::Bodypart_<ContainerAllocator> >::other >  _bodyParts_type;
  _bodyParts_type bodyParts;





  typedef boost::shared_ptr< ::backend::Person_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::backend::Person_<ContainerAllocator> const> ConstPtr;

}; // struct Person_

typedef ::backend::Person_<std::allocator<void> > Person;

typedef boost::shared_ptr< ::backend::Person > PersonPtr;
typedef boost::shared_ptr< ::backend::Person const> PersonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::backend::Person_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::backend::Person_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::backend::Person_<ContainerAllocator1> & lhs, const ::backend::Person_<ContainerAllocator2> & rhs)
{
  return lhs.stationID == rhs.stationID &&
    lhs.sensorID == rhs.sensorID &&
    lhs.bodyParts == rhs.bodyParts;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::backend::Person_<ContainerAllocator1> & lhs, const ::backend::Person_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace backend

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::backend::Person_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::backend::Person_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::backend::Person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::backend::Person_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::backend::Person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::backend::Person_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::backend::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "19e387ec9518ddfc7ac4967934ce1516";
  }

  static const char* value(const ::backend::Person_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x19e387ec9518ddfcULL;
  static const uint64_t static_value2 = 0x7ac4967934ce1516ULL;
};

template<class ContainerAllocator>
struct DataType< ::backend::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "backend/Person";
  }

  static const char* value(const ::backend::Person_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::backend::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A person has some body parts. That is why we have created\n"
"# an array of body parts.\n"
"int16 stationID\n"
"int16 sensorID\n"
"Bodypart[] bodyParts \n"
"\n"
"================================================================================\n"
"MSG: backend/Bodypart\n"
"# The location and score of body parts are stored in a float array.\n"
"# Therefore we are using 32 bits instead of 64 bits.\n"
"# src: https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/include/openpose/core/datum.hpp\n"
"float32 score\n"
"Pixel pixel\n"
"geometry_msgs/Point32 point \n"
"\n"
"================================================================================\n"
"MSG: backend/Pixel\n"
"# The location and score of body parts are stored in a float array.\n"
"# Therefore we are using 32 bits instead of 64 bits.\n"
"# src: https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/include/openpose/core/datum.hpp\n"
"# The location has been resized to the desired output\n"
"# resolution (e.g., `resolution` flag in the demo).\n"
"float32 x\n"
"float32 y \n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::backend::Person_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::backend::Person_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stationID);
      stream.next(m.sensorID);
      stream.next(m.bodyParts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Person_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::backend::Person_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::backend::Person_<ContainerAllocator>& v)
  {
    s << indent << "stationID: ";
    Printer<int16_t>::stream(s, indent + "  ", v.stationID);
    s << indent << "sensorID: ";
    Printer<int16_t>::stream(s, indent + "  ", v.sensorID);
    s << indent << "bodyParts[]" << std::endl;
    for (size_t i = 0; i < v.bodyParts.size(); ++i)
    {
      s << indent << "  bodyParts[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::backend::Bodypart_<ContainerAllocator> >::stream(s, indent + "    ", v.bodyParts[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BACKEND_MESSAGE_PERSON_H
