# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from comparing_system/user_correction.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class user_correction(genpy.Message):
  _md5sum = "f5faadefefb5d277a82a27faf3f41371"
  _type = "comparing_system/user_correction"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# This message describes user correction information

# The following structure reflects the REST API between the Comparing System and the Smtartphone App 
# as specified under https://app.getguru.com/card/iGK7zMAT/Tech-Spec-REST-API-ComparingSystem-Smartphone-App
# For questions, refer to Artur


int16 user_id
int16 repetition
bool positive_correction
string display_text
"""
  __slots__ = ['user_id','repetition','positive_correction','display_text']
  _slot_types = ['int16','int16','bool','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       user_id,repetition,positive_correction,display_text

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(user_correction, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.user_id is None:
        self.user_id = 0
      if self.repetition is None:
        self.repetition = 0
      if self.positive_correction is None:
        self.positive_correction = False
      if self.display_text is None:
        self.display_text = ''
    else:
      self.user_id = 0
      self.repetition = 0
      self.positive_correction = False
      self.display_text = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2hB().pack(_x.user_id, _x.repetition, _x.positive_correction))
      _x = self.display_text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.user_id, _x.repetition, _x.positive_correction,) = _get_struct_2hB().unpack(str[start:end])
      self.positive_correction = bool(self.positive_correction)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.display_text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.display_text = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2hB().pack(_x.user_id, _x.repetition, _x.positive_correction))
      _x = self.display_text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.user_id, _x.repetition, _x.positive_correction,) = _get_struct_2hB().unpack(str[start:end])
      self.positive_correction = bool(self.positive_correction)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.display_text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.display_text = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2hB = None
def _get_struct_2hB():
    global _struct_2hB
    if _struct_2hB is None:
        _struct_2hB = struct.Struct("<2hB")
    return _struct_2hB
