(cl:in-package comparing_system-msg)
(cl:export '(USER_ID-VAL
          USER_ID
          CURRENT_EXERCISE_NAME-VAL
          CURRENT_EXERCISE_NAME
          REPETITIONS-VAL
          REPETITIONS
          SECONDS_SINCE_LAST_EXERCISE_START-VAL
          SECONDS_SINCE_LAST_EXERCISE_START
          MILLISECONDS_SINCE_LAST_REPETITION-VAL
          MILLISECONDS_SINCE_LAST_REPETITION
          REPETITION_SCORE-VAL
          REPETITION_SCORE
          EXERCISE_SCORE-VAL
          EXERCISE_SCORE
          USER_POSITION-VAL
          USER_POSITION
))