# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from backend/Images.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import sensor_msgs.msg
import std_msgs.msg

class Images(genpy.Message):
  _md5sum = "4083fda66ae96557bfd28f8a92b13da6"
  _type = "backend/Images"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 number
sensor_msgs/Image img1
sensor_msgs/Image img2
sensor_msgs/Image img3
sensor_msgs/Image img4

================================================================================
MSG: sensor_msgs/Image
# This message contains an uncompressed image
# (0, 0) is at top-left corner of image
#

Header header        # Header timestamp should be acquisition time of image
                     # Header frame_id should be optical frame of camera
                     # origin of frame should be optical center of camera
                     # +x should point to the right in the image
                     # +y should point down in the image
                     # +z should point into to plane of the image
                     # If the frame_id here and the frame_id of the CameraInfo
                     # message associated with the image conflict
                     # the behavior is undefined

uint32 height         # image height, that is, number of rows
uint32 width          # image width, that is, number of columns

# The legal values for encoding are in file src/image_encodings.cpp
# If you want to standardize a new string format, join
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.

string encoding       # Encoding of pixels -- channel meaning, ordering, size
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h

uint8 is_bigendian    # is this data bigendian?
uint32 step           # Full row length in bytes
uint8[] data          # actual matrix data, size is (step * rows)

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['number','img1','img2','img3','img4']
  _slot_types = ['int16','sensor_msgs/Image','sensor_msgs/Image','sensor_msgs/Image','sensor_msgs/Image']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       number,img1,img2,img3,img4

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Images, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.number is None:
        self.number = 0
      if self.img1 is None:
        self.img1 = sensor_msgs.msg.Image()
      if self.img2 is None:
        self.img2 = sensor_msgs.msg.Image()
      if self.img3 is None:
        self.img3 = sensor_msgs.msg.Image()
      if self.img4 is None:
        self.img4 = sensor_msgs.msg.Image()
    else:
      self.number = 0
      self.img1 = sensor_msgs.msg.Image()
      self.img2 = sensor_msgs.msg.Image()
      self.img3 = sensor_msgs.msg.Image()
      self.img4 = sensor_msgs.msg.Image()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_h3I().pack(_x.number, _x.img1.header.seq, _x.img1.header.stamp.secs, _x.img1.header.stamp.nsecs))
      _x = self.img1.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.img1.height, _x.img1.width))
      _x = self.img1.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BI().pack(_x.img1.is_bigendian, _x.img1.step))
      _x = self.img1.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.img2.header.seq, _x.img2.header.stamp.secs, _x.img2.header.stamp.nsecs))
      _x = self.img2.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.img2.height, _x.img2.width))
      _x = self.img2.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BI().pack(_x.img2.is_bigendian, _x.img2.step))
      _x = self.img2.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.img3.header.seq, _x.img3.header.stamp.secs, _x.img3.header.stamp.nsecs))
      _x = self.img3.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.img3.height, _x.img3.width))
      _x = self.img3.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BI().pack(_x.img3.is_bigendian, _x.img3.step))
      _x = self.img3.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.img4.header.seq, _x.img4.header.stamp.secs, _x.img4.header.stamp.nsecs))
      _x = self.img4.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.img4.height, _x.img4.width))
      _x = self.img4.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BI().pack(_x.img4.is_bigendian, _x.img4.step))
      _x = self.img4.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.img1 is None:
        self.img1 = sensor_msgs.msg.Image()
      if self.img2 is None:
        self.img2 = sensor_msgs.msg.Image()
      if self.img3 is None:
        self.img3 = sensor_msgs.msg.Image()
      if self.img4 is None:
        self.img4 = sensor_msgs.msg.Image()
      end = 0
      _x = self
      start = end
      end += 14
      (_x.number, _x.img1.header.seq, _x.img1.header.stamp.secs, _x.img1.header.stamp.nsecs,) = _get_struct_h3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.img1.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.img1.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.img1.height, _x.img1.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.img1.encoding = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.img1.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.img1.is_bigendian, _x.img1.step,) = _get_struct_BI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img1.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.img2.header.seq, _x.img2.header.stamp.secs, _x.img2.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.img2.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.img2.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.img2.height, _x.img2.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.img2.encoding = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.img2.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.img2.is_bigendian, _x.img2.step,) = _get_struct_BI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img2.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.img3.header.seq, _x.img3.header.stamp.secs, _x.img3.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.img3.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.img3.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.img3.height, _x.img3.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.img3.encoding = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.img3.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.img3.is_bigendian, _x.img3.step,) = _get_struct_BI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img3.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.img4.header.seq, _x.img4.header.stamp.secs, _x.img4.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.img4.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.img4.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.img4.height, _x.img4.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.img4.encoding = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.img4.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.img4.is_bigendian, _x.img4.step,) = _get_struct_BI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img4.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_h3I().pack(_x.number, _x.img1.header.seq, _x.img1.header.stamp.secs, _x.img1.header.stamp.nsecs))
      _x = self.img1.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.img1.height, _x.img1.width))
      _x = self.img1.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BI().pack(_x.img1.is_bigendian, _x.img1.step))
      _x = self.img1.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.img2.header.seq, _x.img2.header.stamp.secs, _x.img2.header.stamp.nsecs))
      _x = self.img2.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.img2.height, _x.img2.width))
      _x = self.img2.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BI().pack(_x.img2.is_bigendian, _x.img2.step))
      _x = self.img2.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.img3.header.seq, _x.img3.header.stamp.secs, _x.img3.header.stamp.nsecs))
      _x = self.img3.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.img3.height, _x.img3.width))
      _x = self.img3.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BI().pack(_x.img3.is_bigendian, _x.img3.step))
      _x = self.img3.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.img4.header.seq, _x.img4.header.stamp.secs, _x.img4.header.stamp.nsecs))
      _x = self.img4.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.img4.height, _x.img4.width))
      _x = self.img4.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BI().pack(_x.img4.is_bigendian, _x.img4.step))
      _x = self.img4.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.img1 is None:
        self.img1 = sensor_msgs.msg.Image()
      if self.img2 is None:
        self.img2 = sensor_msgs.msg.Image()
      if self.img3 is None:
        self.img3 = sensor_msgs.msg.Image()
      if self.img4 is None:
        self.img4 = sensor_msgs.msg.Image()
      end = 0
      _x = self
      start = end
      end += 14
      (_x.number, _x.img1.header.seq, _x.img1.header.stamp.secs, _x.img1.header.stamp.nsecs,) = _get_struct_h3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.img1.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.img1.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.img1.height, _x.img1.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.img1.encoding = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.img1.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.img1.is_bigendian, _x.img1.step,) = _get_struct_BI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img1.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.img2.header.seq, _x.img2.header.stamp.secs, _x.img2.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.img2.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.img2.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.img2.height, _x.img2.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.img2.encoding = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.img2.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.img2.is_bigendian, _x.img2.step,) = _get_struct_BI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img2.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.img3.header.seq, _x.img3.header.stamp.secs, _x.img3.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.img3.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.img3.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.img3.height, _x.img3.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.img3.encoding = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.img3.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.img3.is_bigendian, _x.img3.step,) = _get_struct_BI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img3.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.img4.header.seq, _x.img4.header.stamp.secs, _x.img4.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.img4.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.img4.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.img4.height, _x.img4.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.img4.encoding = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.img4.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.img4.is_bigendian, _x.img4.step,) = _get_struct_BI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img4.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_BI = None
def _get_struct_BI():
    global _struct_BI
    if _struct_BI is None:
        _struct_BI = struct.Struct("<BI")
    return _struct_BI
_struct_h3I = None
def _get_struct_h3I():
    global _struct_h3I
    if _struct_h3I is None:
        _struct_h3I = struct.Struct("<h3I")
    return _struct_h3I
